version: '3'

services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/${BACKEND_IMAGE_NAME}:latest
    ports:
      - "8000:8000"

  frontend:
    image: ${DOCKER_HUB_USERNAME}/${FRONTEND_IMAGE_NAME}:latest
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend