version: '3'

services:
  backend:
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
