name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  BACKEND_IMAGE_NAME: backend
  FRONTEND_IMAGE_NAME: frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd backend/serverside
        pip install -r requirements.txt

    - name: Run Django tests
      run: |
        cd backend/serverside
        python manage.py test
      continue-on-error: true
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run React tests
      run: |
        cd frontend
        npm test
      continue-on-error: true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Only build and push for the main branch
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      run: |
        docker build -t $DOCKER_HUB_USERNAME/$BACKEND_IMAGE_NAME:latest ./backend/serverside
        docker build -t $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE_NAME:latest ./frontend
        docker push $DOCKER_HUB_USERNAME/$BACKEND_IMAGE_NAME:latest
        docker push $DOCKER_HUB_USERNAME/$FRONTEND_IMAGE_NAME:latest